"""Constants for the HelvarNet integration."""

DOMAIN = "helvar"

DEFAULT_ON_GROUP_SCENE = 1
DEFAULT_ON_GROUP_BLOCK = 1
DEFAULT_OFF_GROUP_BLOCK = 1
DEFAULT_OFF_GROUP_SCENE = 15
VALID_OFF_GROUP_SCENES = (15, 16)
